### ISSUE TITLE
Kitty unable to start in Debian 11 (Buster)

### ISSUE THREAD

**Issue by eamccarron** [cbeley/beleyenv#6]
Just installed this on debian 11 (fresh container) and found that kitty was unable to start due to a missing xdg-shell in the compositor.  This can be fixed by changing linux_display_server to x11 in ~/.config/kitty/kitty.conf 

I suspect this issue may re-occur for some other applications and they will similarly need to be forced to use x11 instead of wayland.

**Comment by cbeley** [comment]
I updated kitty and verified that this issue is a new issue with a recent version of kitty. Not sure what changed, but fixed! Thanks for the heads up!

It's unfortunate ChromeOS doesn't support what kitty needs to work with Wayland. :/
